# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "137a6b104d67832b9d464d2251ec0a1c"
name = "ns-rental-manager"
application_url = "https://ns-rental-manager.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://ns-rental-manager.onrender.com/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true
